### ISSUE TITLE
Create basic UI prototype

### ISSUE THREAD

**Issue by JoeProgrammer88** [CPTC-CPW/GameProject#4]
- [ ] Learn how to design a UI
- [ ] Learn event driven programming for the UI (trigger code in scripts)
- [ ] Learn how to style the UI

UI system will be used in battle to perform actions
How will UI be used outside of battle?

**Comment by AnMcCbusiness** [comment]
@AmyshaDixon 
We should start with finding out which direction we want to go outside of combat and then the transition into combat I think. I'm going to run through these tutorials, as well, he following might help with designing the UI: 
[Unity Canvas UI Interface Tutorials](https://unity3d.com/learn/tutorials/topics/user-interface-ui/ui-canvas?playlist=17111)

**Comment by AmyshaDixon** [comment]
@AnMcCbusiness I think that is a great idea! Thank you for the link; I will check it out.
